Fixed CA Cert issue in codebuild
java.security.InvalidAlgorithmParameterException: the trustAnchors
parameter must be non-empty started appearing in codebuild maven builds.
This was due to the Java CA certs not being configured properly.